[workspace]
members = [
    "core-types",
    "crates/engine",
    "apps/desktop",
    "crates/catalog",
    "crates/app-settings",
]

resolver = "2"

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
